// Code generated by Kitex v0.16.3. DO NOT EDIT.

package demoservice

import (
	"context"
	demo "github.com/byx-darwin/go-tools/example/kitex_generated/demo"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streamclient "github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Echo(ctx context.Context, Req *demo.EchoRequest, callOptions ...callopt.Option) (r *demo.EchoResponse, err error)
	Health(ctx context.Context, Req *demo.HealthRequest, callOptions ...callopt.Option) (r *demo.HealthResponse, err error)
	StreamEcho(ctx context.Context, Req *demo.EchoRequest, callOptions ...callopt.Option) (stream DemoService_StreamEchoClient, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	StreamEcho(ctx context.Context, Req *demo.EchoRequest, callOptions ...streamcall.Option) (stream DemoService_StreamEchoClient, err error)
}

type DemoService_StreamEchoClient interface {
	streaming.Stream
	Recv() (*demo.EchoResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDemoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDemoServiceClient struct {
	*kClient
}

func (p *kDemoServiceClient) Echo(ctx context.Context, Req *demo.EchoRequest, callOptions ...callopt.Option) (r *demo.EchoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Echo(ctx, Req)
}

func (p *kDemoServiceClient) Health(ctx context.Context, Req *demo.HealthRequest, callOptions ...callopt.Option) (r *demo.HealthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx, Req)
}

func (p *kDemoServiceClient) StreamEcho(ctx context.Context, Req *demo.EchoRequest, callOptions ...callopt.Option) (stream DemoService_StreamEchoClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StreamEcho(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDemoServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDemoServiceStreamClient struct {
	*kClient
}

func (p *kDemoServiceStreamClient) StreamEcho(ctx context.Context, Req *demo.EchoRequest, callOptions ...streamcall.Option) (stream DemoService_StreamEchoClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.StreamEcho(ctx, Req)
}
