// Code generated by Kitex v0.16.1. DO NOT EDIT.

package demoservice

import (
	"context"
	demo "github.com/byx-darwin/go-tools/example/kitex_generated/demo"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Echo(ctx context.Context, Req *demo.EchoRequest, callOptions ...callopt.Option) (r *demo.EchoResponse, err error)
	Health(ctx context.Context, Req *demo.HealthRequest, callOptions ...callopt.Option) (r *demo.HealthResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDemoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDemoServiceClient struct {
	*kClient
}

func (p *kDemoServiceClient) Echo(ctx context.Context, Req *demo.EchoRequest, callOptions ...callopt.Option) (r *demo.EchoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Echo(ctx, Req)
}

func (p *kDemoServiceClient) Health(ctx context.Context, Req *demo.HealthRequest, callOptions ...callopt.Option) (r *demo.HealthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx, Req)
}
