// Code generated by Kitex v0.16.3. DO NOT EDIT.

package demoservice

import (
	"context"
	"errors"
	"fmt"
	demo "github.com/byx-darwin/go-tools/example/kitex_generated/demo"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Echo": kitex.NewMethodInfo(
		echoHandler,
		newEchoArgs,
		newEchoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newHealthArgs,
		newHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"StreamEcho": kitex.NewMethodInfo(
		streamEchoHandler,
		newStreamEchoArgs,
		newStreamEchoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
}

var (
	demoServiceServiceInfo                = NewServiceInfo()
	demoServiceServiceInfoForClient       = NewServiceInfoForClient()
	demoServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return demoServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return demoServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return demoServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DemoService"
	handlerType := (*demo.DemoService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "demo",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(demo.EchoRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(demo.DemoService).Echo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EchoArgs:
		success, err := handler.(demo.DemoService).Echo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EchoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEchoArgs() interface{} {
	return &EchoArgs{}
}

func newEchoResult() interface{} {
	return &EchoResult{}
}

type EchoArgs struct {
	Req *demo.EchoRequest
}

func (p *EchoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoArgs) Unmarshal(in []byte) error {
	msg := new(demo.EchoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoArgs_Req_DEFAULT *demo.EchoRequest

func (p *EchoArgs) GetReq() *demo.EchoRequest {
	if !p.IsSetReq() {
		return EchoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoResult struct {
	Success *demo.EchoResponse
}

var EchoResult_Success_DEFAULT *demo.EchoResponse

func (p *EchoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoResult) Unmarshal(in []byte) error {
	msg := new(demo.EchoResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoResult) GetSuccess() *demo.EchoResponse {
	if !p.IsSetSuccess() {
		return EchoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*demo.EchoResponse)
}

func (p *EchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoResult) GetResult() interface{} {
	return p.Success
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(demo.HealthRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(demo.DemoService).Health(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HealthArgs:
		success, err := handler.(demo.DemoService).Health(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HealthResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHealthArgs() interface{} {
	return &HealthArgs{}
}

func newHealthResult() interface{} {
	return &HealthResult{}
}

type HealthArgs struct {
	Req *demo.HealthRequest
}

func (p *HealthArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HealthArgs) Unmarshal(in []byte) error {
	msg := new(demo.HealthRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HealthArgs_Req_DEFAULT *demo.HealthRequest

func (p *HealthArgs) GetReq() *demo.HealthRequest {
	if !p.IsSetReq() {
		return HealthArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HealthArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HealthArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HealthResult struct {
	Success *demo.HealthResponse
}

var HealthResult_Success_DEFAULT *demo.HealthResponse

func (p *HealthResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HealthResult) Unmarshal(in []byte) error {
	msg := new(demo.HealthResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HealthResult) GetSuccess() *demo.HealthResponse {
	if !p.IsSetSuccess() {
		return HealthResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HealthResult) SetSuccess(x interface{}) {
	p.Success = x.(*demo.HealthResponse)
}

func (p *HealthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HealthResult) GetResult() interface{} {
	return p.Success
}

func streamEchoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &demoServiceStreamEchoServer{st}
	req := new(demo.EchoRequest)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(demo.DemoService).StreamEcho(req, stream)
}

type demoServiceStreamEchoClient struct {
	streaming.Stream
}

func (x *demoServiceStreamEchoClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *demoServiceStreamEchoClient) Recv() (*demo.EchoResponse, error) {
	m := new(demo.EchoResponse)
	return m, x.Stream.RecvMsg(m)
}

type demoServiceStreamEchoServer struct {
	streaming.Stream
}

func (x *demoServiceStreamEchoServer) Send(m *demo.EchoResponse) error {
	return x.Stream.SendMsg(m)
}

func newStreamEchoArgs() interface{} {
	return &StreamEchoArgs{}
}

func newStreamEchoResult() interface{} {
	return &StreamEchoResult{}
}

type StreamEchoArgs struct {
	Req *demo.EchoRequest
}

func (p *StreamEchoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *StreamEchoArgs) Unmarshal(in []byte) error {
	msg := new(demo.EchoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var StreamEchoArgs_Req_DEFAULT *demo.EchoRequest

func (p *StreamEchoArgs) GetReq() *demo.EchoRequest {
	if !p.IsSetReq() {
		return StreamEchoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *StreamEchoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StreamEchoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type StreamEchoResult struct {
	Success *demo.EchoResponse
}

var StreamEchoResult_Success_DEFAULT *demo.EchoResponse

func (p *StreamEchoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *StreamEchoResult) Unmarshal(in []byte) error {
	msg := new(demo.EchoResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *StreamEchoResult) GetSuccess() *demo.EchoResponse {
	if !p.IsSetSuccess() {
		return StreamEchoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *StreamEchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*demo.EchoResponse)
}

func (p *StreamEchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StreamEchoResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, Req *demo.EchoRequest) (r *demo.EchoResponse, err error) {
	var _args EchoArgs
	_args.Req = Req
	var _result EchoResult
	if err = p.c.Call(ctx, "Echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context, Req *demo.HealthRequest) (r *demo.HealthResponse, err error) {
	var _args HealthArgs
	_args.Req = Req
	var _result HealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StreamEcho(ctx context.Context, req *demo.EchoRequest) (DemoService_StreamEchoClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "StreamEcho", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &demoServiceStreamEchoClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}
