// Code generated by Kitex v0.16.1. DO NOT EDIT.

package demo

import (
	"context"

	"github.com/cloudwego/prutal"
)

type EchoRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *EchoRequest) Reset() { *x = EchoRequest{} }

func (x *EchoRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EchoRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Service string `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
}

func (x *EchoResponse) Reset() { *x = EchoResponse{} }

func (x *EchoResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EchoResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthRequest struct {
}

func (x *HealthRequest) Reset() { *x = HealthRequest{} }

func (x *HealthRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HealthRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type HealthResponse struct {
	Healthy bool   `protobuf:"varint,1,opt,name=healthy" json:"healthy,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (x *HealthResponse) Reset() { *x = HealthResponse{} }

func (x *HealthResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HealthResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DemoService interface {
	Echo(ctx context.Context, req *EchoRequest) (res *EchoResponse, err error)
	Health(ctx context.Context, req *HealthRequest) (res *HealthResponse, err error)
}
